### ISSUE TITLE
Method not allowed with post request

### ISSUE THREAD

**Issue by Dodecanom** [shamblett/coap#103]
Hello,

I’m trying to connect to my Ikea lights with Flutter. My issue is that when I try to do a post request the response is `Code: 4.05 Method Not Allowed` which is weird because a post request should be allowed.

When I do the exact same request from command line there is no issue (with the SECURITY_CODE and PRE_SHARED_KEY replaced of course) :

Request: `coap-client-openssl -m post -u "Client_identity" -k "SECURITY_CODE" -e '{"9090":"IDENTITY"}' "coaps://192.168.1.41:5684/15011/9063"`
Response: `{"9091":"PRE_SHARED_KEY","9029":"1.19.0026"}`

Could you have a look to my code and tell me what’s wrong? I would be very grateful if you could help me to get this working, I really want to play with this!

If you are curious the request I try to do is the one described here: https://github.com/home-assistant-libs/pytradfri/issues/90

Here is a minimum example followed by my pubspec

```dart
import 'package:flutter/material.dart';
import 'package:coap/coap.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Test lights',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: const TestWidget());
  }
}

class TestWidget extends StatefulWidget {
  const TestWidget({
    Key? key,
  }) : super(key: key);

  @override
  State<TestWidget> createState() => _TestWidgetState();
}

class _TestWidgetState extends State<TestWidget> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: TextButton(
          child: const Text('Test button'),
          onPressed: () async {
            final conf = DtlsConfig();

            var credentials = PskCredentials(
              identity: 'Client_identity',
              preSharedKey: 'SECURITY_CODE',
            );

            PskCredentials pskCredentialsCallback(final String indentity) => credentials;

            final uri = Uri(
              scheme: 'coaps',
              host: '192.168.1.41',
              port: conf.defaultSecurePort,
            );

            final client = CoapClient(
              uri,
              conf,
              pskCredentialsCallback: pskCredentialsCallback,
            );

            try {
              client.events.on<Object>().listen(print);

              final response = await client.post(
                '15011/9063',
                payload: '{"9090":"IDENTITY"}',
              );
            } on Exception catch (e) {
              print('CoAP encountered an exception: $e');
            }

            client.close();
          },
        ),
      ),
    );
  }
}

class DtlsConfig extends DefaultCoapConfig {
  @override
  final dtlsBackend = DtlsBackend.TinyDtls;
}
```

```yaml
name: auto_lights
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  coap: ^4.1.0
  dart_tinydtls_libs: ^0.1.1
  dart_tinydtls: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

```
